service: helloservice
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
